require('dotenv').config();
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');const {URL}=require('url');
const PORT=Number(process.env.PORT||3000),CLIENT_ID=process.env.DISCORD_CLIENT_ID||'',CLIENT_SECRET=process.env.DISCORD_CLIENT_SECRET||'',REDIRECT_URI=process.env.DISCORD_REDIRECT_URI||`http://localhost:${PORT}/auth/discord/callback`;
const DATA=path.join(__dirname,'data');const FILE=path.join(DATA,'players.json');const sessions=new Map();if(!fs.existsSync(DATA))fs.mkdirSync(DATA,{recursive:true});if(!fs.existsSync(FILE))fs.writeFileSync(FILE,'{}');
const read=()=>JSON.parse(fs.readFileSync(FILE,'utf8')||'{}');const write=x=>fs.writeFileSync(FILE,JSON.stringify(x,null,2));
function cookies(req){const o={};for(const p of String(req.headers.cookie||'').split(';')){const [k,...r]=p.trim().split('=');if(k)o[k]=decodeURIComponent(r.join('=')||'')}return o}
function send(res,s,b,h={}){res.writeHead(s,{'Content-Type':'application/json; charset=utf-8',...h});res.end(JSON.stringify(b))}function red(res,u,h=[]){res.writeHead(302,{Location:u,'Set-Cookie':h});res.end()}
function body(req){return new Promise((ok,bad)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>ok(s));req.on('error',bad)})}
async function token(code){const p=new URLSearchParams({client_id:CLIENT_ID,client_secret:CLIENT_SECRET,grant_type:'authorization_code',code,redirect_uri:REDIRECT_URI});const r=await fetch('https://discord.com/api/v10/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p});if(!r.ok)throw Error('token exchange');return r.json()}
async function me(t){const r=await fetch('https://discord.com/api/v10/users/@me',{headers:{Authorization:`Bearer ${t}`}});if(!r.ok)throw Error('user lookup');return r.json()}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,`http://${req.headers.host}`);
if(req.method==='GET'&&u.pathname==='/auth/discord'){const state=crypto.randomBytes(24).toString('hex');sessions.set('oauth:'+state,Date.now());const a=new URL('https://discord.com/oauth2/authorize');a.searchParams.set('client_id',CLIENT_ID);a.searchParams.set('response_type','code');a.searchParams.set('redirect_uri',REDIRECT_URI);a.searchParams.set('scope','identify');a.searchParams.set('state',state);return red(res,a.toString(),[`oauth_state=${state}; HttpOnly; SameSite=Lax; Path=/`])}
if(req.method==='GET'&&u.pathname==='/auth/discord/callback'){const c=cookies(req),state=u.searchParams.get('state'),code=u.searchParams.get('code');if(!state||c.oauth_state!==state||!sessions.has('oauth:'+state))return send(res,400,{error:'Invalid OAuth state'});sessions.delete('oauth:'+state);const t=await token(code),user=await me(t.access_token),sid=crypto.randomBytes(32).toString('hex');sessions.set(sid,{userId:user.id});const all=read();if(!all[user.id])all[user.id]={discord:user,save:{best:0,coins:0,maxLevel:1,maxCombo:0,shoe:0,upgrades:{speed:0,power:0,control:0}}};else all[user.id].discord=user;write(all);return red(res,'/?login=success',[`ts_session=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000`,'oauth_state=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'])}
if(req.method==='POST'&&u.pathname==='/auth/logout'){const c=cookies(req);if(c.ts_session)sessions.delete(c.ts_session);return send(res,200,{ok:true},{'Set-Cookie':'ts_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'})}
if(req.method==='GET'&&u.pathname==='/api/me'){const ses=sessions.get(cookies(req).ts_session);if(!ses)return send(res,200,{loggedIn:false});const all=read(),x=all[ses.userId];return send(res,200,{loggedIn:true,user:x.discord,save:x.save})}
if(req.method==='POST'&&u.pathname==='/api/save'){const ses=sessions.get(cookies(req).ts_session);if(!ses)return send(res,401,{error:'Discord ile giriş yapmalısın.'});let q=JSON.parse(await body(req)||'{}');const all=read();all[ses.userId].save={best:Math.max(0,+q.best||0),coins:Math.max(0,+q.coins||0),maxLevel:Math.max(1,+q.maxLevel||1),maxCombo:Math.max(0,+q.maxCombo||0),shoe:Math.max(0,+q.shoe||0),upgrades:{speed:Math.max(0,Math.min(5,+q.upgrades?.speed||0)),power:Math.max(0,Math.min(5,+q.upgrades?.power||0)),control:Math.max(0,Math.min(5,+q.upgrades?.control||0))}};write(all);return send(res,200,{ok:true,save:all[ses.userId].save})}
let fp=u.pathname==='/'?path.join(__dirname,'index.html'):path.normalize(path.join(__dirname,u.pathname));if(!fp.startsWith(__dirname)||!fs.existsSync(fp))return send(res,404,{error:'Not found'});const ext=path.extname(fp);const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(fp).pipe(res);}catch(e){console.error(e);send(res,500,{error:'Server error'})}});server.listen(PORT,()=>console.log(`http://localhost:${PORT}`));